backend:
  image:
    repository: ghcr.io/nashtech-garage/shopdi-customer
    tag: latest

  nameOverride: customer
  fullnameOverride: customer
  databaseName: customer
  ingress:
    enabled: false
  extraEnvFroms:
    - secretRef:
        name: shopdi-keycloak-credentials-secret
  extraVolumes:
    - name: customer-application
      configMap:
        name: customer-application-configmap
  extraVolumeMounts:
    - name: customer-application
      mountPath: /opt/shopdi/customer
  extraApplicationConfigPaths:
    - /opt/shopdi/customer/customer-application.yaml
