backend:
  image:
    repository: ghcr.io/nashtech-garage/shopdi-inventory
    tag: latest

  nameOverride: inventory
  fullnameOverride: inventory
  databaseName: inventory
  ingress:
    enabled: false
