version: "3.9"

services:
  nginx:
    image:  nginx:1.27.2
    restart: unless-stopped
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/configuration/custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf
    ports:
      - "80:80"
    networks:
      - shopdi-network
  identity:
    image: quay.io/keycloak/keycloak:26.0.2
    command: 'start-dev --import-realm'
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_HTTP_PORT: 80
    volumes:
      - ./identity/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./identity/themes/shopdi/theme:/opt/keycloak/themes
    networks:
      - shopdi-network
  backoffice:
    build: ./backoffice-bff
    image: ghcr.io/nashtech-garage/shopdi-backoffice-bff:latest
    entrypoint: ["./wait-for-it.sh", "identity:80", "--timeout=300", "--", "java", "-jar", "/app.jar"]
    environment:
    - SPRING_PROFILES_ACTIVE=prod
    - SERVER_PORT
    - LOGGING_CONFIG
    - JAVA_TOOL_OPTIONS
    - OTEL_EXPORTER_OTLP_ENDPOINT
    - OTEL_EXPORTER_OTLP_PROTOCOL
    - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
    - OTEL_RESOURCE_ATTRIBUTES
    - OTEL_SERVICE_NAME=backoffice-bff-service
    - OTEL_LOGS_EXPORTER
    - OTEL_TRACES_EXPORTER
    - OTEL_METRICS_EXPORTER
    - OTEL_INSTRUMENTATION_LOGBACK-MDC_ADD-BAGGAGE
    - OTEL_JAVAAGENT_LOGGING
    - OTEL_JAVAAGENT_ENABLED
    - OTEL_JAVAAGENT_DEBUG
    volumes:
    - ./docker/libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
    - ./deployment/app-config:/app-config
    networks:
      - shopdi-network
  backoffice-nextjs:
    image: ghcr.io/nashtech-garage/shopdi-backoffice:latest
    networks:
    - shopdi-network
  storefront:
    build: ./storefront-bff
    image: ghcr.io/nashtech-garage/shopdi-storefront-bff:latest
    entrypoint: ["./wait-for-it.sh", "identity:80", "--timeout=300", "--", "java", "-jar", "/app.jar"]
    environment:
    - SPRING_PROFILES_ACTIVE=prod
    - SHOPDI_SERVICES_CUSTOMER
    - SHOPDI_SERVICES_CART
    - SHOPDI_SERVICES_RATING
    - SHOPDI_SERVICES_ORDER
    - SHOPDI_SERVICES_LOCATION
    - SHOPDI_SERVICES_INVENTORY
    - SHOPDI_SERVICES_TAX
    - SHOPDI_SERVICES_PROMOTION
    - SHOPDI_SERVICES_PAYMENT
    - SHOPDI_SERVICES_SAMPLE_DATA
    - SERVER_PORT
    - LOGGING_CONFIG
    - JAVA_TOOL_OPTIONS
    - OTEL_EXPORTER_OTLP_ENDPOINT
    - OTEL_EXPORTER_OTLP_PROTOCOL
    - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
    - OTEL_RESOURCE_ATTRIBUTES
    - OTEL_SERVICE_NAME=storefront-bff-service
    - OTEL_LOGS_EXPORTER
    - OTEL_TRACES_EXPORTER
    - OTEL_METRICS_EXPORTER
    - OTEL_INSTRUMENTATION_LOGBACK-MDC_ADD-BAGGAGE
    - OTEL_JAVAAGENT_LOGGING
    - OTEL_JAVAAGENT_ENABLED
    - OTEL_JAVAAGENT_DEBUG
    volumes:
    - ./docker/libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
    - ./deployment/app-config:/app-config      
    networks:
      - shopdi-network
  storefront-nextjs:
    image: ghcr.io/nashtech-garage/shopdi-storefront:latest
    networks:
      - shopdi-network
  media:
    build: ./media  
    image: ghcr.io/nashtech-garage/shopdi-media:latest
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/media
    - SERVER_SERVLET_CONTEXT_PATH=/media
    - SHOPDI_PUBLIC_URL=${SHOPDI_PUBLIC_API_URL}/media
    - SERVER_PORT
    - LOGGING_CONFIG
    - JAVA_TOOL_OPTIONS
    - OTEL_EXPORTER_OTLP_ENDPOINT
    - OTEL_EXPORTER_OTLP_PROTOCOL
    - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
    - OTEL_RESOURCE_ATTRIBUTES
    - OTEL_SERVICE_NAME=media-service
    - OTEL_LOGS_EXPORTER
    - OTEL_TRACES_EXPORTER
    - OTEL_METRICS_EXPORTER
    - OTEL_INSTRUMENTATION_LOGBACK-MDC_ADD-BAGGAGE
    - OTEL_JAVAAGENT_LOGGING
    - OTEL_JAVAAGENT_ENABLED
    - OTEL_JAVAAGENT_DEBUG
    volumes:
    - ./docker/libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
    - ./deployment/app-config:/app-config
    - ./sampledata/images:/images
    networks:
      - shopdi-network
  product:
    build: ./product
    image: ghcr.io/nashtech-garage/shopdi-product:latest
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/product
    - SERVER_SERVLET_CONTEXT_PATH=/product
    - SHOPDI_SERVICES_MEDIA
    - SERVER_PORT
    - LOGGING_CONFIG
    - JAVA_TOOL_OPTIONS    
    - OTEL_EXPORTER_OTLP_ENDPOINT
    - OTEL_EXPORTER_OTLP_PROTOCOL
    - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
    - OTEL_RESOURCE_ATTRIBUTES
    - OTEL_SERVICE_NAME=product-service
    - OTEL_LOGS_EXPORTER
    - OTEL_TRACES_EXPORTER
    - OTEL_METRICS_EXPORTER
    - OTEL_INSTRUMENTATION_LOGBACK-MDC_ADD-BAGGAGE
    - OTEL_JAVAAGENT_LOGGING
    - OTEL_JAVAAGENT_ENABLED
    - OTEL_JAVAAGENT_DEBUG
    volumes:
    - ./docker/libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
    - ./deployment/app-config:/app-config
    networks:
      - shopdi-network
  customer:
    build: ./customer  
    image: ghcr.io/nashtech-garage/shopdi-customer:latest
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/customer
    - SERVER_SERVLET_CONTEXT_PATH=/customer
    - SHOPDI_SERVICES_LOCATION
    - SERVER_PORT
    - LOGGING_CONFIG
    - JAVA_TOOL_OPTIONS    
    - OTEL_EXPORTER_OTLP_ENDPOINT
    - OTEL_EXPORTER_OTLP_PROTOCOL
    - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
    - OTEL_RESOURCE_ATTRIBUTES
    - OTEL_SERVICE_NAME=customer-service
    - OTEL_LOGS_EXPORTER
    - OTEL_TRACES_EXPORTER
    - OTEL_METRICS_EXPORTER
    - OTEL_INSTRUMENTATION_LOGBACK-MDC_ADD-BAGGAGE
    - OTEL_JAVAAGENT_LOGGING
    - OTEL_JAVAAGENT_ENABLED
    - OTEL_JAVAAGENT_DEBUG
    volumes:
    - ./docker/libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
    - ./deployment/app-config:/app-config
    networks:
      - shopdi-network
  cart:
    build: ./cart
    image: ghcr.io/nashtech-garage/shopdi-cart:latest
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/cart
    - SERVER_SERVLET_CONTEXT_PATH=/cart
    - SHOPDI_SERVICES_MEDIA
    - SHOPDI_SERVICES_PRODUCT
    - SERVER_PORT
    - LOGGING_CONFIG
    - JAVA_TOOL_OPTIONS
    - OTEL_EXPORTER_OTLP_ENDPOINT
    - OTEL_EXPORTER_OTLP_PROTOCOL
    - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
    - OTEL_RESOURCE_ATTRIBUTES
    - OTEL_SERVICE_NAME=cart-service
    - OTEL_LOGS_EXPORTER
    - OTEL_TRACES_EXPORTER
    - OTEL_METRICS_EXPORTER
    - OTEL_INSTRUMENTATION_LOGBACK-MDC_ADD-BAGGAGE
    - OTEL_JAVAAGENT_LOGGING
    - OTEL_JAVAAGENT_ENABLED
    - OTEL_JAVAAGENT_DEBUG
    volumes:
    - ./docker/libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
    - ./deployment/app-config:/app-config
    networks:
      - shopdi-network
  rating:
    build: ./rating  
    image: ghcr.io/nashtech-garage/shopdi-rating:latest
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/rating
    - SERVER_SERVLET_CONTEXT_PATH=/rating
    - SHOPDI_PUBLIC_URL=${SHOPDI_PUBLIC_API_URL}/rating
    - SHOPDI_SERVICES_PRODUCT
    - SHOPDI_SERVICES_CUSTOMER
    - SHOPDI_SERVICES_ORDER
    - SERVER_PORT
    - LOGGING_CONFIG
    - JAVA_TOOL_OPTIONS
    - OTEL_EXPORTER_OTLP_ENDPOINT
    - OTEL_EXPORTER_OTLP_PROTOCOL
    - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
    - OTEL_RESOURCE_ATTRIBUTES
    - OTEL_SERVICE_NAME=rate-service
    - OTEL_LOGS_EXPORTER
    - OTEL_TRACES_EXPORTER
    - OTEL_METRICS_EXPORTER
    - OTEL_INSTRUMENTATION_LOGBACK-MDC_ADD-BAGGAGE
    - OTEL_JAVAAGENT_LOGGING
    - OTEL_JAVAAGENT_ENABLED
    - OTEL_JAVAAGENT_DEBUG
    volumes:
    - ./docker/libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
    - ./deployment/app-config:/app-config
    networks:
      - shopdi-network
  order:
    build: ./order
    image: ghcr.io/nashtech-garage/shopdi-order:latest
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/order
    - SERVER_SERVLET_CONTEXT_PATH=/order
    - SERVER_PORT
    - LOGGING_CONFIG
    - JAVA_TOOL_OPTIONS        
    - SHOPDI_PUBLIC_URL=${SHOPDI_PUBLIC_API_URL}/order
    - SHOPDI_SERVICES_CART
    - SHOPDI_SERVICES_CUSTOMER
    - SHOPDI_SERVICES_PRODUCT
    - SHOPDI_SERVICES_TAX
    - OTEL_EXPORTER_OTLP_ENDPOINT
    - OTEL_EXPORTER_OTLP_PROTOCOL
    - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
    - OTEL_RESOURCE_ATTRIBUTES
    - OTEL_SERVICE_NAME=order-service
    - OTEL_LOGS_EXPORTER
    - OTEL_TRACES_EXPORTER
    - OTEL_METRICS_EXPORTER
    - OTEL_JAVAAGENT_LOGGING
    - OTEL_JAVAAGENT_ENABLED
    - OTEL_JAVAAGENT_DEBUG
    - OTEL_INSTRUMENTATION_LOGBACK-MDC_ADD-BAGGAGE
    - SHOPDI_CURRENCY_UNIT
    - SHOPDI_PRICE_INCLUDES_TAX
    volumes:
    - ./docker/libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
    - ./deployment/app-config:/app-config
    networks:
      - shopdi-network
  payment:
    build: ./payment
    image: ghcr.io/nashtech-garage/shopdi-payment:latest
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/payment
    - SERVER_SERVLET_CONTEXT_PATH=/payment
    - SHOPDI_PUBLIC_URL=${SHOPDI_PUBLIC_API_URL}/payment
    - SHOPDI_SERVICES_ORDER
    - SHOPDI_SERVICES_MEDIA
    - SERVER_PORT
    - LOGGING_CONFIG
    - JAVA_TOOL_OPTIONS
    - OTEL_EXPORTER_OTLP_ENDPOINT
    - OTEL_EXPORTER_OTLP_PROTOCOL
    - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
    - OTEL_RESOURCE_ATTRIBUTES
    - OTEL_SERVICE_NAME=payment-service
    - OTEL_LOGS_EXPORTER
    - OTEL_TRACES_EXPORTER
    - OTEL_METRICS_EXPORTER
    - OTEL_INSTRUMENTATION_LOGBACK-MDC_ADD-BAGGAGE
    - OTEL_JAVAAGENT_LOGGING
    - OTEL_JAVAAGENT_ENABLED
    - OTEL_JAVAAGENT_DEBUG
    - SHOPDI_CURRENCY_UNIT
    - SHOPDI_PRICE_INCLUDES_TAX
    volumes:
    - ./docker/libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
    - ./deployment/app-config:/app-config
    networks:
      - shopdi-network
  location:
    build: ./location
    image: ghcr.io/nashtech-garage/shopdi-location:latest
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/location
    - SERVER_SERVLET_CONTEXT_PATH=/location
    - SHOPDI_PUBLIC_URL=${SHOPDI_PUBLIC_API_URL}/location
    - SERVER_PORT
    - LOGGING_CONFIG
    - JAVA_TOOL_OPTIONS
    - OTEL_EXPORTER_OTLP_ENDPOINT
    - OTEL_EXPORTER_OTLP_PROTOCOL
    - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
    - OTEL_RESOURCE_ATTRIBUTES
    - OTEL_SERVICE_NAME=location-service
    - OTEL_LOGS_EXPORTER
    - OTEL_TRACES_EXPORTER
    - OTEL_METRICS_EXPORTER
    - OTEL_INSTRUMENTATION_LOGBACK-MDC_ADD-BAGGAGE
    - OTEL_JAVAAGENT_LOGGING
    - OTEL_JAVAAGENT_ENABLED
    - OTEL_JAVAAGENT_DEBUG
    volumes:
    - ./docker/libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
    - ./deployment/app-config:/app-config
    networks:
      - shopdi-network
  inventory:
    build: ./inventory
    image: ghcr.io/nashtech-garage/shopdi-inventory:latest
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/inventory
    - SERVER_SERVLET_CONTEXT_PATH=/inventory
    - SHOPDI_PUBLIC_URL=${SHOPDI_PUBLIC_API_URL}/inventory
    - SHOPDI_SERVICES_PRODUCT
    - SHOPDI_SERVICES_LOCATION
    - SERVER_PORT
    - LOGGING_CONFIG
    - JAVA_TOOL_OPTIONS
    - OTEL_EXPORTER_OTLP_ENDPOINT
    - OTEL_EXPORTER_OTLP_PROTOCOL
    - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
    - OTEL_RESOURCE_ATTRIBUTES
    - OTEL_SERVICE_NAME=inventory-service
    - OTEL_LOGS_EXPORTER
    - OTEL_TRACES_EXPORTER
    - OTEL_METRICS_EXPORTER
    - OTEL_INSTRUMENTATION_LOGBACK-MDC_ADD-BAGGAGE
    - OTEL_JAVAAGENT_LOGGING
    - OTEL_JAVAAGENT_ENABLED
    - OTEL_JAVAAGENT_DEBUG
    volumes:
    - ./docker/libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
    - ./deployment/app-config:/app-config
    networks:
      - shopdi-network
  promotion:
    build: ./promotion  
    image: ghcr.io/nashtech-garage/shopdi-promotion:latest
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/promotion
    - SERVER_SERVLET_CONTEXT_PATH=/promotion
    - SHOPDI_PUBLIC_URL=${SHOPDI_PUBLIC_API_URL}/promotion
    - SHOPDI_SERVICES_PRODUCT
    - SERVER_PORT
    - LOGGING_CONFIG
    - JAVA_TOOL_OPTIONS
    - OTEL_EXPORTER_OTLP_ENDPOINT
    - OTEL_EXPORTER_OTLP_PROTOCOL
    - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
    - OTEL_RESOURCE_ATTRIBUTES
    - OTEL_SERVICE_NAME=promotion-service
    - OTEL_LOGS_EXPORTER
    - OTEL_TRACES_EXPORTER
    - OTEL_METRICS_EXPORTER
    - OTEL_INSTRUMENTATION_LOGBACK-MDC_ADD-BAGGAGE
    - OTEL_JAVAAGENT_LOGGING
    - OTEL_JAVAAGENT_ENABLED
    - OTEL_JAVAAGENT_DEBUG
    volumes:
    - ./docker/libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
    - ./deployment/app-config:/app-config      
    networks:
      - shopdi-network
  tax:
    build: ./tax    
    image: ghcr.io/nashtech-garage/shopdi-tax:latest
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/tax
    - SERVER_SERVLET_CONTEXT_PATH=/tax
    - SHOPDI_PUBLIC_URL=${SHOPDI_PUBLIC_API_URL}/tax
    - SHOPDI_SERVICES_LOCATION
    - SERVER_PORT
    - LOGGING_CONFIG
    - JAVA_TOOL_OPTIONS
    - OTEL_EXPORTER_OTLP_ENDPOINT
    - OTEL_EXPORTER_OTLP_PROTOCOL
    - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
    - OTEL_RESOURCE_ATTRIBUTES
    - OTEL_SERVICE_NAME=tax-service
    - OTEL_LOGS_EXPORTER
    - OTEL_TRACES_EXPORTER
    - OTEL_METRICS_EXPORTER
    - OTEL_INSTRUMENTATION_LOGBACK-MDC_ADD-BAGGAGE
    - OTEL_JAVAAGENT_LOGGING
    - OTEL_JAVAAGENT_ENABLED
    - OTEL_JAVAAGENT_DEBUG
    volumes:
    - ./docker/libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
    - ./deployment/app-config:/app-config
    networks:
    - shopdi-network
  sampledata:
    build: ./sampledata
    image: ghcr.io/nashtech-garage/shopdi-sampledata:latest
    environment:
      - SPRING_DATASOURCE_PRODUCT_URL=jdbc:postgresql://postgres:5432/product
      - SPRING_DATASOURCE_MEDIA_URL=jdbc:postgresql://postgres:5432/media
      - SERVER_SERVLET_CONTEXT_PATH=/sampledata
      - SHOPDI_PUBLIC_URL=${SHOPDI_PUBLIC_API_URL}/sampledata
      - SHOPDI_SERVICES_SAMPLE_DATA
      - SERVER_PORT
      - LOGGING_CONFIG
      - JAVA_TOOL_OPTIONS
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_PROTOCOL
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
      - OTEL_RESOURCE_ATTRIBUTES
      - OTEL_SERVICE_NAME=sampledata-service
      - OTEL_LOGS_EXPORTER
      - OTEL_TRACES_EXPORTER
      - OTEL_METRICS_EXPORTER
      - OTEL_INSTRUMENTATION_LOGBACK-MDC_ADD-BAGGAGE
      - OTEL_JAVAAGENT_LOGGING
      - OTEL_JAVAAGENT_ENABLED
      - OTEL_JAVAAGENT_DEBUG
    volumes:
      - ./docker/libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
      - ./deployment/app-config:/app-config
    networks:
      - shopdi-network
  # webhook:
  #   build: ./webhook
  #   image: ghcr.io/nashtech-garage/shopdi-webhook:latest
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/webhook
  #     - SERVER_SERVLET_CONTEXT_PATH=/webhook
  #     - SHOPDI_PUBLIC_URL=${SHOPDI_PUBLIC_API_URL}/webhook
  #     - SHOPDI_SERVICES_LOCATION
  #     - SERVER_PORT
  #     - LOGGING_CONFIG
  #     - JAVA_TOOL_OPTIONS
  #     - OTEL_EXPORTER_OTLP_ENDPOINT
  #     - OTEL_EXPORTER_OTLP_PROTOCOL
  #     - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
  #     - OTEL_RESOURCE_ATTRIBUTES
  #     - OTEL_SERVICE_NAME=webhook-service
  #     - OTEL_LOGS_EXPORTER
  #     - OTEL_TRACES_EXPORTER
  #     - OTEL_METRICS_EXPORTER
  #     - OTEL_INSTRUMENTATION_LOGBACK-MDC_ADD-BAGGAGE
  #     - OTEL_JAVAAGENT_LOGGING
  #     - OTEL_JAVAAGENT_ENABLED
  #     - OTEL_JAVAAGENT_DEBUG
  #   volumes:
  #     - ./docker/libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
  #     - ./deployment/app-config:/app-config
  #   networks:
  #     - shopdi-network
  # recommendation:
  #   build: ./recommendation
  #   image: ghcr.io/nashtech-garage/shopdi-recommendation:latest
  #   ports:
  #     - '9791:9791'
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/recommendation
  #     - SERVER_SERVLET_CONTEXT_PATH=/recommendation
  #     - SHOPDI_PUBLIC_URL=${SHOPDI_PUBLIC_API_URL}/recommendation
  #     - SHOPDI_SERVICES_PRODUCT
  #     - SERVER_PORT
  #     - LOGGING_CONFIG
  #     - JAVA_TOOL_OPTIONS
  #     - OTEL_EXPORTER_OTLP_ENDPOINT
  #     - OTEL_EXPORTER_OTLP_PROTOCOL
  #     - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
  #     - OTEL_RESOURCE_ATTRIBUTES
  #     - OTEL_SERVICE_NAME=recommendation-service
  #     - OTEL_LOGS_EXPORTER
  #     - OTEL_TRACES_EXPORTER
  #     - OTEL_METRICS_EXPORTER
  #     - OTEL_INSTRUMENTATION_LOGBACK-MDC_ADD-BAGGAGE
  #     - OTEL_JAVAAGENT_LOGGING
  #     - OTEL_JAVAAGENT_ENABLED
  #     - OTEL_JAVAAGENT_DEBUG
  #     # OpenAI Config
  #     - SPRING_AI_AZURE_OPENAI_API_KEY
  #     - SPRING_AI_AZURE_OPENAI_ENDPOINT
  #     - SPRING_AI_AZURE_OPENAI_EMBEDDING_OPTIONS_MODEL
  #   volumes:
  #     - ./docker/libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
  #     - ./deployment/app-config:/app-config
  #   networks:
  #     - shopdi-network
  swagger-ui:
    image: swaggerapi/swagger-ui:v5.17.14
    environment:
    - BASE_URL=/swagger-ui
    - URLS
    - OAUTH_CLIENT_ID=swagger-ui
    - OAUTH_USE_PKCE=true
    networks:
      - shopdi-network
  postgres:
    image: debezium/postgres:16-alpine
    build: ./docker/postgres
    hostname: ${POSTGRES_HOST}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./docker/postgres/postgresql.conf.sample:/usr/share/postgresql/postgresql.conf.sample
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
      - postgres:/var/lib/postgresql/data
    command: postgres -c 'max_connections=500'
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - shopdi-network
  pgadmin:
    image: dpage/pgadmin4:2024-10-19-2
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@shopdi.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - shopdi-network
  zookeeper:
    image: debezium/zookeeper:2.7.3.Final
    restart: always
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - shopdi-network
  kafka:
    image: confluentinc/cp-kafka:7.7.1
    hostname: ${KAFKA_SERVICE_HOST}
    depends_on:
      - zookeeper
    ports:
      - ${KAFKA_SERVICE_PORT}:${KAFKA_SERVICE_PORT}
      - 29092:29092
    environment:
      - KAFKA_BROKER_ID
      - KAFKA_ZOOKEEPER_CONNECT
      - KAFKA_ADVERTISED_LISTENERS
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      - KAFKA_INTER_BROKER_LISTENER_NAME
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
    networks:
      - shopdi-network
  kafka-connect:
    image: debezium/connect:2.7.3.Final
    restart: always
    ports:
      - 8083:8083
      - 5005:5005
    depends_on:
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=kafka_connect_configs
      - OFFSET_STORAGE_TOPIC=kafka_connect_offsets
    networks:
      - shopdi-network
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - 8089:8080
    depends_on:
      - kafka
      - kafka-connect
    networks:
      - shopdi-network
  redis:
    image: redis:7.4.1-alpine
    restart: always
    ports:
      - '6379:6379'
    environment:
      - SPRING_DATA_REDIS_HOST
      - SPRING_DATA_REDIS_PORT
    volumes:
      - redis:/data
    networks:
      - shopdi-network

networks:
  shopdi-network:
    driver: bridge
    name: shopdi-network

volumes:
  postgres:
  pgadmin:
  redis: