hostname: identity.shopdi.local.com
backofficeRedirectUrl: http://backoffice.shopdi.local.com
storefrontRedirectUrl: http://storefront.shopdi.local.com
postgresql:
  username: shopdiadminuser
  password: admin

bootstrapAdmin:
  username: admin
  password: admin
