backend:
  image:
    repository: ghcr.io/nashtech-garage/shopdi-search
    tag: latest

  nameOverride: search
  fullnameOverride: search
  databaseName: search
  ingress:
    enabled: false
  extraEnvFroms:
    - secretRef:
        name: shopdi-elasticsearch-credentials-secret
  extraVolumes:
    - name: search-application
      configMap:
        name: search-application-configmap
  extraVolumeMounts:
    - name: search-application
      mountPath: /opt/shopdi/search
  extraApplicationConfigPaths:
    - /opt/shopdi/search/search-application.yaml
