domain: shopdi.local.com
postgresql:
  replicas: 1
  username: shopdiadminuser
  password: admin
kafka:
  replicas: 1
zookeeper:
  replicas: 1
elasticsearch:
  replicas: 1
  username: shopdi
  password: LarUmB3A49NTg9YmgW4=
keycloak:
  bootstrapAdmin:
    username: admin
    password: admin
  backofficeRedirectUrl: http://backoffice.shopdi.local.com
  storefrontRedirectUrl: http://storefront.shopdi.local.com
grafana:
  username: admin
  password: admin
redis:
  password: redis
