backend:
  image:
    repository: ghcr.io/nashtech-garage/shopdi-product
    tag: latest

  nameOverride: product
  fullnameOverride: product
  databaseName: product
  ingress:
    enabled: false
  extraVolumes:
    - name: product-application-config
      configMap:
        name: product-application-configmap
  extraVolumeMounts:
    - name: product-application-config
      mountPath: /opt/shopdi/product
  extraApplicationConfigPaths:
    - /opt/shopdi/product/product-application.yaml
