backend:
  image:
    repository: ghcr.io/nashtech-garage/shopdi-promotion
    tag: latest

  nameOverride: promotion
  fullnameOverride: promotion
  databaseName: promotion
  ingress:
    enabled: false
