backend:
  image:
    repository: ghcr.io/nashtech-garage/shopdi-recommendation
    tag: latest

  nameOverride: recommendation
  fullnameOverride: recommendation
  databaseName: recommendation
  ingress:
    enabled: false
  extraEnvFroms:
    - secretRef:
        name: shopdi-openai-api-key-secret
  extraVolumes:
    - name: recommendation-application
      configMap:
        name: recommendation-application-configmap
  extraVolumeMounts:
    - name: recommendation-application
      mountPath: /opt/shopdi/recommendation
  extraApplicationConfigPaths:
    - /opt/shopdi/recommendation/recommendation-application.yaml
