backend:
  image:
    repository: ghcr.io/nashtech-garage/shopdi-order
    tag: latest

  nameOverride: order
  fullnameOverride: order
  databaseName: order
  ingress:
    enabled: false
  extraVolumes:
    - name: order-application-config
      configMap:
        name: order-application-configmap
  extraVolumeMounts:
    - name: order-application-config
      mountPath: /opt/shopdi/order
  extraApplicationConfigPaths:
    - /opt/shopdi/order/order-application.yaml
