hostname: &hostname grafana.shopdi.local.com
prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true
grafana:
  grafana.ini:
    database:
      type: postgres
      host: postgresql.postgres:5432
      name: grafana
      user: shopdiadminuser
      password: admin
      ssl_mode: require
  adminUser: admin
  adminPassword: admin
  ingress:
    ingressClassName: nginx
    enabled: true
    hosts:
      - *hostname
