backend:
  image:
    repository: ghcr.io/nashtech-garage/shopdi-payment
    tag: latest

  nameOverride: payment
  fullnameOverride: payment
  databaseName: payment
  ingress:
    enabled: false
  extraVolumes:
    - name: payment-application-config
      configMap:
        name: payment-application-configmap
  extraVolumeMounts:
    - name: payment-application-config
      mountPath: /opt/shopdi/payment
  extraApplicationConfigPaths:
    - /opt/shopdi/payment/payment-application.yaml
