backend:
  image:
    repository: ghcr.io/nashtech-garage/shopdi-media
    tag: latest

  nameOverride: media
  fullnameOverride: media
  databaseName: media
  ingress:
    enabled: false
  extraVolumes:
    - name: media-application
      configMap:
        name: media-application-configmap
  extraVolumeMounts:
    - name: media-application
      mountPath: /opt/shopdi/media
  extraApplicationConfigPaths:
    - /opt/shopdi/media/media-application.yaml
