backend:
  image:
    repository: ghcr.io/nashtech-garage/shopdi-{{service}}
    tag: latest

  nameOverride: { { service } }
  fullnameOverride: { { service } }
  databaseName: { { service } }

  ingress:
    enabled: true
    host: api.shopdi.local.com
    path: /{{service}}
