backend:
  image:
    repository: ghcr.io/nashtech-garage/shopdi-cart
    tag: latest

  nameOverride: cart
  fullnameOverride: cart
  databaseName: cart
  ingress:
    enabled: false
  extraVolumes:
    - name: cart-application-config
      configMap:
        name: cart-application-configmap
  extraVolumeMounts:
    - name: cart-application-config
      mountPath: /opt/shopdi/cart
  extraApplicationConfigPaths:
    - /opt/shopdi/cart/cart-application.yaml
