backend:
  image:
    repository: ghcr.io/nashtech-garage/shopdi-backoffice-bff
    tag: latest

  nameOverride: backoffice-bff
  fullnameOverride: backoffice-bff
  deployment:
    annotations:
      configmap.reloader.stakater.com/reload: "shopdi-gateway-routes-config-configmap,backoffice-bff-extra-configmap"
  ingress:
    enabled: true
    host: backoffice.shopdi.local.com
    path: /
  extraEnvs:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: UI_HOST
      value: http://backoffice-ui:3000
  extraEnvFroms:
    - secretRef:
        name: shopdi-keycloak-credentials-secret
    - secretRef:
        name: shopdi-redis-credentials-secret
  extraVolumes:
    - name: shopdi-gateway-routes-config
      configMap:
        name: shopdi-gateway-routes-config-configmap
    - name: backoffice-bff-extra-config
      configMap:
        name: backoffice-bff-extra-configmap
  extraVolumeMounts:
    - name: shopdi-gateway-routes-config
      mountPath: /opt/shopdi/gateway-routes-config
    - name: backoffice-bff-extra-config
      mountPath: /opt/shopdi/extra-config
  extraApplicationConfigPaths:
    - /opt/shopdi/gateway-routes-config/gateway-routes-config.yaml
    - /opt/shopdi/extra-config/backoffice-bff-extra-config.yaml
