backend:
  image:
    repository: ghcr.io/nashtech-garage/shopdi-sampledata
    tag: latest

  nameOverride: sampledata
  fullnameOverride: sampledata
  databaseName: sampledata
  ingress:
    enabled: false
  extraVolumes:
    - name: sampledata-application
      configMap:
        name: sampledata-application-configmap
  extraVolumeMounts:
    - name: sampledata-application
      mountPath: /opt/shopdi/sampledata
  extraApplicationConfigPaths:
    - /opt/shopdi/sampledata/sampledata-application.yaml
