backend:
  image:
    repository: ghcr.io/nashtech-garage/shopdi-payment-paypal
    tag: latest

  nameOverride: payment-paypal
  fullnameOverride: payment-paypal
  databaseName: payment-paypal
  ingress:
    enabled: false
  extraVolumes:
    - name: payment-paypal-application-config
      configMap:
        name: payment-paypal-application-configmap
  extraVolumeMounts:
    - name: payment-paypal-application-config
      mountPath: /opt/shopdi/payment-paypal
  extraApplicationConfigPaths:
    - /opt/shopdi/payment-paypal/payment-paypal-application.yaml
